"""Add screening_status to CandidateApplication

Revision ID: 7c05a3cbc49b
Revises: 9a0e3f9bbc96
Create Date: 2025-07-26 22:57:22.503808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c05a3cbc49b'
down_revision: Union[str, Sequence[str], None] = '9a0e3f9bbc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_applications', sa.Column('screening_status', sa.String(
        length=20), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_applications', 'screening_status')
    # ### end Alembic commands ###
