"""update_assessment_status_default_to_in_progress

Revision ID: b0994a0cb0a0
Revises: 11160bb3c74f
Create Date: 2025-07-29 13:11:39.333195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0994a0cb0a0'
down_revision: Union[str, Sequence[str], None] = '11160bb3c74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add database-level default for status column
    op.alter_column('assessments', 'status',
                    server_default='in_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove database-level default for status column
    op.alter_column('assessments', 'status',
                    server_default=None)
    # ### end Alembic commands ###
