"""update_assessment_table_changes

Revision ID: b7ac54cc67d6
Revises: 0f3170e5d262
Create Date: 2025-07-28 00:21:04.102984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ac54cc67d6'
down_revision: Union[str, Sequence[str], None] = '0f3170e5d262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'current_question_index')
    op.drop_column('assessments', 'time_taken_minutes')
    op.drop_column('assessments', 'total_questions')
    op.drop_column('assessments', 'time_limit_minutes')
    op.drop_column('assessments', 'max_possible_score')
    op.drop_column('assessments', 'total_score')
    op.drop_column('assessments', 'answers_data')
    op.drop_column('assessments', 'skill_assessment_data')
    op.drop_column('assessments', 'questions_answered')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('questions_answered', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('skill_assessment_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('answers_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('total_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('max_possible_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('time_limit_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('time_taken_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('current_question_index', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
