"""add_report_column_to_assessment_table

Revision ID: 11160bb3c74f
Revises: b7ac54cc67d6
Create Date: 2025-07-28 13:18:20.923620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11160bb3c74f'
down_revision: Union[str, Sequence[str], None] = 'b7ac54cc67d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'report')
    # ### end Alembic commands ###
